"""机床控制接口：区分 STM 独占的 Z/放电能力与上位机看到的整机能力。"""

from __future__ import annotations

from typing import Protocol

from .domain import MachineConfig, MachineStatus


class ZController(Protocol):
    """独立 STM 下位机负责 Z 运动和穿孔；不要求其实现 LinuxCNC XY。"""

    def status(self) -> MachineStatus: ...

    def apply_config(self, config: MachineConfig) -> None: ...

    def home_z(self) -> None: ...

    def set_surface_zero(self) -> None: ...

    def jog_z(self, delta_mm: float) -> None: ...

    def move_z_absolute(self, target_mm: float) -> None: ...

    def arm_hole(self, recipe_id: int, depth_mm: float) -> None: ...

    def start_hole(self) -> None: ...

    def stop(self) -> None: ...

    def emergency_stop(self) -> None: ...

    def reset_fault(self) -> None: ...

    def tick(self, elapsed_s: float) -> None: ...

    @property
    def completed_holes(self) -> int: ...


class Controller(ZController, Protocol):
    """JobService/手动页看到的组合整机接口。"""

    def home_xy(self) -> None: ...

    def move_xy(self, x_mm: float, y_mm: float) -> None: ...

    def manual_move_xy(self, x_mm: float, y_mm: float) -> None: ...

    def jog_xy(self, dx_mm: float, dy_mm: float) -> None: ...

    def set_work_coordinates(self, x_mm: float | None = None, y_mm: float | None = None) -> None: ...

    def set_flush(self, enabled: bool) -> None: ...

    def set_rotation(self, enabled: bool) -> None: ...

    def set_pulse(self, enabled: bool) -> None: ...

    def supports_manual_output(self, name: str) -> bool: ...

    @property
    def xy_in_position(self) -> bool: ...
